#!/usr/bin/env python3
"""Build a blind adjudication packet from ledger/ledger.md (Gap Register Priority 32).

For every adversarial check ("Strongest innocent reading" / "Strongest good-faith reading"),
emit the entry text from its nearest heading up to and including the innocent reading,
and OMIT the proposer's verdict ("Why this reading fails/succeeds ...") and everything after.
The adjudicator sees the case for the classification and the case against it, not the ruling.
"""
import re, sys, hashlib, pathlib

SRC = pathlib.Path("ledger/ledger.md")
OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "docs/handoffs/blind-adjudication-packet.md")
lines = SRC.read_text().splitlines()
src_hash = hashlib.sha256(SRC.read_bytes()).hexdigest()

reading = re.compile(r"^\s*\**Strongest (innocent|good-faith)[^:]*reading[^:]*:", re.I)
heading = re.compile(r"^(#{2,4} |\*\*(ENTRY|Entry|TB-|TC-|TD-|TE-|TF-|PATTERN|Pattern Registry Entry|CTF)[^*]*\*\*)")
MAXLINES = 60
verdict = re.compile(r"^\s*\**Why (this|the) reading", re.I)

items = []
for i, ln in enumerate(lines):
    if not reading.match(ln):
        continue
    start = i
    while start > 0 and lines[start].strip() != "---" and not heading.match(lines[start]):
        start -= 1
    if lines[start].strip() == "---":
        start += 1
    truncated = False
    if i - start > MAXLINES:
        start, truncated = i - MAXLINES, True
    body = lines[start:i + 1]
    if truncated:
        body = ["*[Span truncated to the last %d lines before the innocent reading.]*" % MAXLINES] + body
    # drop any earlier verdict lines inside the span (multi-check entries)
    body = [b for b in body if not verdict.match(b)]
    items.append((start + 1, i + 1, lines[start].strip()[:140], "\n".join(body)))

out = [
    "# Blind Adjudication Packet: ledger adversarial checks",
    "",
    f"*Generated by `scripts/build_blind_adjudication_packet.py` from `ledger/ledger.md` "
    f"(sha256 `{src_hash[:16]}…`). {len(items)} checks. Each item ends at the innocent reading; "
    "the proposer's verdict has been removed.*",
    "",
    "**Known limit:** the entry text preceding each innocent reading was written by the proposer "
    "and argues for the classification. The packet removes the ruling, not the advocacy.",
    "",
]
for n, (s, e, h, body) in enumerate(items, 1):
    out += [f"---\n\n## Check C{n:02d}  (ledger lines {s}–{e})", "", f"**Entry heading:** {h}", "", body, ""]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out) + "\n")
print(f"{len(items)} checks -> {OUT} ({OUT.stat().st_size//1024} KB)")
